services:
  opshub-app:
    build:
      context: .
      dockerfile: src/Ctg.OpsHub.Api/Containerfile

  opshub-gateway:
    build:
      context: .
      dockerfile: src/Ctg.OpsHub.Gateway/Containerfile
    depends_on:
      - opshub-app

  opshub-nginx:
    image: docker.io/library/nginx:stable-alpine
    ports:
      - "8336:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - opshub-gateway